{
  "comments": [
    {
      "key": {
        "uuid": "05c24b7c_b12d9491",
        "filename": "appengine/swarming/handlers_bot_test.py",
        "patchSetId": 4
      },
      "lineNbr": 287,
      "author": {
        "id": 1161379
      },
      "writtenOn": "2020-08-19T00:35:21Z",
      "side": 1,
      "message": "I think this is bug in client and better to raise BadRequest exception?",
      "range": {
        "startLine": 287,
        "startChar": 36,
        "endLine": 287,
        "endChar": 41
      },
      "revId": "8a79a7bc425f35b8438562a031e9b66c6ce3f70a",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}