{
  "comments": [
    {
      "key": {
        "uuid": "d311f3d6_15b39619",
        "filename": "/COMMIT_MSG",
        "patchSetId": 17
      },
      "lineNbr": 9,
      "author": {
        "id": 1161379
      },
      "writtenOn": "2020-07-01T06:51:10Z",
      "side": 1,
      "message": "do you know why this build didn\u0027t fail with test failure?\nhttps://ci.chromium.org/p/infra/builders/try/luci-py-try-mac10.13-64/b8876002613344674176",
      "revId": "cdd1c1f7d0292ed34fe9fea4d97c48273699f3b3",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "4de0e192_81e3e4d6",
        "filename": "/COMMIT_MSG",
        "patchSetId": 17
      },
      "lineNbr": 9,
      "author": {
        "id": 1366072
      },
      "writtenOn": "2020-07-01T06:53:52Z",
      "side": 1,
      "message": "It failed, but the exit code is currently ignored.\nhttps://logs.chromium.org/logs/infra/buildbucket/cr-buildbucket.appspot.com/8876002613344674176/+/u/swarming_bot/run_tests_python2/stdout#L3967_0\n\ncrrev.com/c/2275562 will enable exit code check.",
      "parentUuid": "d311f3d6_15b39619",
      "revId": "cdd1c1f7d0292ed34fe9fea4d97c48273699f3b3",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "919502d6_e270739c",
        "filename": "/COMMIT_MSG",
        "patchSetId": 17
      },
      "lineNbr": 9,
      "author": {
        "id": 1161379
      },
      "writtenOn": "2020-07-01T07:04:16Z",
      "side": 1,
      "message": "Then why the step failed on mac10.15?\nhttps://ci.chromium.org/p/infra/builders/try/luci-py-try-mac10.15-64/b8875999708777059248",
      "parentUuid": "4de0e192_81e3e4d6",
      "revId": "cdd1c1f7d0292ed34fe9fea4d97c48273699f3b3",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "b1545e87_3e34570f",
        "filename": "/COMMIT_MSG",
        "patchSetId": 17
      },
      "lineNbr": 9,
      "author": {
        "id": 1366072
      },
      "writtenOn": "2020-07-01T07:13:40Z",
      "side": 1,
      "message": "\u003e It failed, but the exit code is currently ignored.\n\nThis explanation was wrong.\nCurrently it checks exit code for the *Python2* step. (the Python3 step ignores exit code)\nBut the step on Mac10.13 returned exit code 0 for some reason...\nhttps://logs.chromium.org/logs/infra/buildbucket/cr-buildbucket.appspot.com/8876002613344674176/+/u/swarming_bot/run_tests_python2/execution_details#L3971_0",
      "parentUuid": "919502d6_e270739c",
      "revId": "cdd1c1f7d0292ed34fe9fea4d97c48273699f3b3",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "1241a13f_86b94b1a",
        "filename": "/COMMIT_MSG",
        "patchSetId": 17
      },
      "lineNbr": 9,
      "author": {
        "id": 1161379
      },
      "writtenOn": "2020-07-01T08:14:11Z",
      "side": 1,
      "message": "does that fail with non-zero exit code if other test failed?",
      "parentUuid": "b1545e87_3e34570f",
      "revId": "cdd1c1f7d0292ed34fe9fea4d97c48273699f3b3",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "f23f7420_3e21b400",
        "filename": "/COMMIT_MSG",
        "patchSetId": 17
      },
      "lineNbr": 9,
      "author": {
        "id": 1366072
      },
      "writtenOn": "2020-07-01T08:55:41Z",
      "side": 1,
      "message": "I think so. I saw it failed at some patches.\nhttps://ci.chromium.org/p/infra/builders/try/luci-py-try-mac10.13-64/b8876005717178358304?",
      "parentUuid": "1241a13f_86b94b1a",
      "revId": "cdd1c1f7d0292ed34fe9fea4d97c48273699f3b3",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "6e7b781c_9fae68fa",
        "filename": "appengine/swarming/swarming_bot/bot_code/task_runner_test.py",
        "patchSetId": 17
      },
      "lineNbr": 706,
      "author": {
        "id": 1161379
      },
      "writtenOn": "2020-07-01T08:14:11Z",
      "side": 1,
      "message": "better to keep running some already passed test?",
      "revId": "cdd1c1f7d0292ed34fe9fea4d97c48273699f3b3",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "a0731fea_9b584405",
        "filename": "appengine/swarming/swarming_bot/bot_code/task_runner_test.py",
        "patchSetId": 17
      },
      "lineNbr": 706,
      "author": {
        "id": 1366072
      },
      "writtenOn": "2020-07-01T08:55:41Z",
      "side": 1,
      "message": "Done",
      "parentUuid": "6e7b781c_9fae68fa",
      "revId": "cdd1c1f7d0292ed34fe9fea4d97c48273699f3b3",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": false
    }
  ]
}