{
  "comments": [
    {
      "key": {
        "uuid": "93b74b2c_e92c602f",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1366072
      },
      "writtenOn": "2020-09-18T06:56:08Z",
      "side": 1,
      "message": "Please give early feedback on this CL. \nI\u0027m not confident with cache cleanup part.",
      "revId": "d3f37eb0788ed1be41d42f894207c7784a2cea6f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "4ea2d772_b6e73e4b",
        "filename": "client/run_isolated.py",
        "patchSetId": 3
      },
      "lineNbr": 1549,
      "author": {
        "id": 1161379
      },
      "writtenOn": "2020-09-18T07:07:06Z",
      "side": 1,
      "message": "I prefer not to keep commented out code.",
      "range": {
        "startLine": 1543,
        "startChar": 0,
        "endLine": 1549,
        "endChar": 27
      },
      "revId": "d3f37eb0788ed1be41d42f894207c7784a2cea6f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "73f1eea7_a49c18e2",
        "filename": "client/run_isolated.py",
        "patchSetId": 3
      },
      "lineNbr": 1553,
      "author": {
        "id": 1161379
      },
      "writtenOn": "2020-09-18T07:07:06Z",
      "side": 1,
      "message": "no need to have this?",
      "range": {
        "startLine": 1553,
        "startChar": 45,
        "endLine": 1553,
        "endChar": 53
      },
      "revId": "d3f37eb0788ed1be41d42f894207c7784a2cea6f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "6ea6ad44_96de30f4",
        "filename": "client/run_isolated.py",
        "patchSetId": 3
      },
      "lineNbr": 1681,
      "author": {
        "id": 1366072
      },
      "writtenOn": "2020-09-18T06:56:08Z",
      "side": 1,
      "message": "Please review this part carefully as it caused outage last year.",
      "range": {
        "startLine": 1676,
        "startChar": 0,
        "endLine": 1681,
        "endChar": 62
      },
      "revId": "d3f37eb0788ed1be41d42f894207c7784a2cea6f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "474dfaef_14b96b6b",
        "filename": "client/run_isolated.py",
        "patchSetId": 3
      },
      "lineNbr": 1726,
      "author": {
        "id": 1366072
      },
      "writtenOn": "2020-09-18T06:56:08Z",
      "side": 1,
      "message": "When does `cas_cache` need to be included in caches?",
      "range": {
        "startLine": 1723,
        "startChar": 0,
        "endLine": 1726,
        "endChar": 15
      },
      "revId": "d3f37eb0788ed1be41d42f894207c7784a2cea6f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "bb3cd439_25467c50",
        "filename": "client/run_isolated.py",
        "patchSetId": 3
      },
      "lineNbr": 1726,
      "author": {
        "id": 1161379
      },
      "writtenOn": "2020-09-18T07:07:06Z",
      "side": 1,
      "message": "this line needs to have both.",
      "parentUuid": "474dfaef_14b96b6b",
      "range": {
        "startLine": 1723,
        "startChar": 0,
        "endLine": 1726,
        "endChar": 15
      },
      "revId": "d3f37eb0788ed1be41d42f894207c7784a2cea6f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "5c69b44b_cc5e8ce9",
        "filename": "client/run_isolated.py",
        "patchSetId": 3
      },
      "lineNbr": 1726,
      "author": {
        "id": 1366072
      },
      "writtenOn": "2020-09-18T07:13:28Z",
      "side": 1,
      "message": "Assuming named_cache is given, are the following expectations correct?\n\n1) use_go_isolated\ncaches \u003d [cas_cache, named_cache]\n\n2) otherwise\ncaches \u003d [isolate_cache, cas_cache, named_cache]\n\nIf so, the line 1676-1681 are wrong.",
      "parentUuid": "bb3cd439_25467c50",
      "range": {
        "startLine": 1723,
        "startChar": 0,
        "endLine": 1726,
        "endChar": 15
      },
      "revId": "d3f37eb0788ed1be41d42f894207c7784a2cea6f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "fd0f4636_32cdcb6f",
        "filename": "client/run_isolated.py",
        "patchSetId": 3
      },
      "lineNbr": 1726,
      "author": {
        "id": 1161379
      },
      "writtenOn": "2020-09-18T07:17:55Z",
      "side": 1,
      "message": "I think this should be always 2).",
      "parentUuid": "5c69b44b_cc5e8ce9",
      "range": {
        "startLine": 1723,
        "startChar": 0,
        "endLine": 1726,
        "endChar": 15
      },
      "revId": "d3f37eb0788ed1be41d42f894207c7784a2cea6f",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}