{
  "comments": [
    {
      "key": {
        "uuid": "1a961aa1_4bdb03f2",
        "filename": "appengine/swarming/server/resultdb.py",
        "patchSetId": 5
      },
      "lineNbr": 15,
      "author": {
        "id": 1114299
      },
      "writtenOn": "2020-04-28T15:03:59Z",
      "side": 1,
      "message": "both functions should be async, otherwise i don\u0027t see how you can make these RPCs concurrently with datastore access",
      "revId": "f4dedad0a440bde7607e59e805b10e429b10e3fc",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "cd2797d1_3bd16620",
        "filename": "appengine/swarming/server/resultdb.py",
        "patchSetId": 5
      },
      "lineNbr": 32,
      "author": {
        "id": 1114299
      },
      "writtenOn": "2020-04-28T15:03:59Z",
      "side": 1,
      "message": "nit: should be response_headers\u003dresponse_headers because the param is optional",
      "range": {
        "startLine": 32,
        "startChar": 9,
        "endLine": 32,
        "endChar": 25
      },
      "revId": "f4dedad0a440bde7607e59e805b10e429b10e3fc",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "997dcada_f2ae538d",
        "filename": "appengine/swarming/server/resultdb.py",
        "patchSetId": 5
      },
      "lineNbr": 54,
      "author": {
        "id": 1366072
      },
      "writtenOn": "2020-04-28T13:47:02Z",
      "side": 1,
      "message": "Leave logs for this path?",
      "revId": "f4dedad0a440bde7607e59e805b10e429b10e3fc",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "907d1ddb_2f58dae2",
        "filename": "appengine/swarming/server/resultdb.py",
        "patchSetId": 5
      },
      "lineNbr": 54,
      "author": {
        "id": 1114299
      },
      "writtenOn": "2020-04-28T15:03:59Z",
      "side": 1,
      "message": "yes, let\u0027s not lose data - let\u0027s log the error with logging.exception",
      "parentUuid": "997dcada_f2ae538d",
      "revId": "f4dedad0a440bde7607e59e805b10e429b10e3fc",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "f48998b9_c84d5165",
        "filename": "appengine/swarming/server/resultdb.py",
        "patchSetId": 5
      },
      "lineNbr": 63,
      "author": {
        "id": 1114299
      },
      "writtenOn": "2020-04-28T15:03:59Z",
      "side": 1,
      "message": "this raises a ValueError exception if resultdb wasn\u0027t enabled (i.e rdb_url is \u0027\u0027), which can be confusing. Consider\n\n  assert rdb_url, \u0027ResultDB integration is not configured\u0027\n\nbefore this line",
      "revId": "f4dedad0a440bde7607e59e805b10e429b10e3fc",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba",
      "unresolved": true
    }
  ]
}